# 1. 重命名！避免与 nginx.conf 内置的 main 冲突
log_format webhook_access '$remote_addr - $time_iso8601 "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" $request_time';

# 2. Body 打印格式（这个名字不会冲突，保留不变）
log_format webhook_body '=== ZLM CALLBACK BODY ===\n'
                        'TIME: $time_iso8601\n'
                        'URI: $uri\n'
                        'BODY: $request_body\n'
                        '=========================';

server {
    listen 80;
    server_name localhost;

    # 3. 引用新的格式名称
    access_log /dev/stdout webhook_access;
    error_log /dev/stderr warn;

    location /webhook/ {
        client_max_body_size 10m;
        mirror /logger;
        mirror_request_body on;

        default_type application/json;
        return 200 '{"code": 0, "msg": "success"}';
    }

    location /webhook/on_stream_none_reader {
        client_max_body_size 10m;
        mirror /logger;
        mirror_request_body on;

        default_type application/json;
        return 200 '{"code": 0, "close": true }';
    }


    location = /logger {
        internal;
        access_log /dev/stderr webhook_body;
        return 204;
    }
}
